---

###
### Lints all generic and json files in the whole git repository
###

name: building
on:
  pull_request:
  push:
    branches:
      - master
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        version:
          - '2.7'
          - '3.5'
          - '3.6'
          - '3.7'
          - '3.8'

    name: "[${{ matrix.version }}]"
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Build source distribution
        run: |
          make _build-source_dist PYTHON_VERSION=${version}
        env:
          version: ${{ matrix.version }}

      - name: Build binary distribution
        run: |
          make _build-binary_dist PYTHON_VERSION=${version}
        env:
          version: ${{ matrix.version }}

      - name: Build Python package
        run: |
          make _build-python_package PYTHON_VERSION=${version}
        env:
          version: ${{ matrix.version }}
