---

###
### Lints all generic and json files in the whole git repository
###

name: linting
on:
  pull_request:
  push:
    branches:
      - master
    tags:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        target:
          - Linting
    name: "[ ${{ matrix.target }} ]"
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Lint files
        run: |
          make _lint-files

      - name: "Check equal version in CHANGELOG.md, setup.py and pwncat -v"
        run: |
          make _lint-version

      - name: "Check equal usage in README.md and pwncat -h"
        run: |
          make _lint-usage

      - name: Check up-to-date docs
        run: |
          make _lint-docs

      - name: Check up-to-date man page
        run: |
          make _lint-man

      - name: Check up-to-date GitHub Action workflows
        run: |
          make _lint-flows
